### ISSUE TITLE
Same poster with different resolution download

### ISSUE THREAD

**Issue by canberkozcelik** [yvzzztrk/mposter-android#3]
We can't download same poster by changing poster resolution from settings, we should update the icons `ic_download` and `ic_eye` after resolution changed.

Steps to reproduce:
- download any media, download icon will be change to eye
- change resolution from settings
- try to download same media
- eye button toggles could not download

Acceptance Criteria:
Same poster with different resolutions should be downloadable.

**Comment by yvzzztrk** [comment]
LOL NICE CATCH.

**Comment by yvzzztrk** [comment]
I got this.
If we save posters with "imdbId_resolution", Ex: tt1234_1500.png, then should able to download different resolution. I will close this issue when I fix it.

**Comment by yvzzztrk** [comment]
fixed. Commit --> 29da7df1380844679b6c19cfe90108ef42453a7f
