### ISSUE TITLE
Disable selecting default application on sharing media

### ISSUE THREAD

**Issue by canberkozcelik** [yvzzztrk/mposter-android#8]
Some devices asking choose default app as alert dialog,

Acceptance Criteria:
User can be share media with different apps without facing any alert

**Comment by yvzzztrk** [comment]
Intent.createChooser(sendIntent, "Share Using...")

**Comment by yvzzztrk** [comment]
fixed.
https://github.com/yvzzztrk/mposter-android/commit/e121d334a156fb30a58dd915e655b0c4b5d4d47e
